// <auto-generated />
using System;
using ApiSampleIncludes.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiSampleIncludes.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20210204002120_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ApiSampleIncludes.Models.ContaFinanceira", b =>
                {
                    b.Property<int>("ContaFinanceiraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<string>("NomeConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("ContaFinanceiraId");

                    b.HasIndex("PessoaId");

                    b.ToTable("ContaFinanceira");
                });

            modelBuilder.Entity("ApiSampleIncludes.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("ApiSampleIncludes.Models.ContaFinanceira", b =>
                {
                    b.HasOne("ApiSampleIncludes.Models.Pessoa", "Pessoa")
                        .WithMany("ContaFinanceira")
                        .HasForeignKey("PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ApiSampleIncludes.Models.Pessoa", b =>
                {
                    b.Navigation("ContaFinanceira");
                });
#pragma warning restore 612, 618
        }
    }
}
